# Intro to Numpy arrays
This Notebook will walk you through the basics of working with NumPy arrays in Python. NumPy arrays are like lists in some ways, but they can only contain a single data type and they can have more than one dimension!


First, import the NumPy library:

In [2]:
import numpy as np

<br>
Now, let's create our first array using the np.array() function. Make a one dimensional NumPy array with five integers of your choice and assign it to a variable: 

In [3]:
# Here's an example: myArray = np.array([2, 73, 4, 1, 203])
myArray = np.array([5, 20, 73, 444, 3])

<br>
Print the array and its data type. Then print only the second value in the array and its data type.

In [4]:
print(myArray)
print(type(myArray))

[  5  20  73 444   3]
<class 'numpy.ndarray'>


You can use indexes to refer to a single value from a NumPy array. Print out the first and last item in your array using indexes:

In [5]:
print(myArray[0])
print(myArray[4])

5
3


Print out the data type for one of the items in your array:

In [6]:
print(type(myArray[2]))

<class 'numpy.int64'>


We can specify the datatype for our array. Redefine your array with an additional argument: dtype=np.float64.

*Note: You can find the entire list of possible data types here: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html*

In [7]:
# example: myArray = np.array([2, 73, 4, 1, 203], dtype=np.float64)
myArray = np.array([5, 20, 73, 444, 3], dtype=np.float64)

Print out the array and its data type again:

In [8]:
print(myArray)
print(type(myArray))

[  5.  20.  73. 444.   3.]
<class 'numpy.ndarray'>


Now print the second value in the array and its data type:

In [9]:
print(myArray[1])
print(type(myArray[1]))

20.0
<class 'numpy.float64'>


Finally, calculate and print the mean value of your array:

In [10]:
print(np.mean(myArray))

109.0


## Arrays with more dimensions
We can create empty NumPy arrays of specific dimensions using np.empty() or np.zeros(). 

Create a 2 X 4 array of zeros by specifying the dimensions inside of square brackets:

In [11]:
# Example: np.zeros([2,5]) would create an empty 2 X 5 array
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

We can think of an array of dimensions [2,4] as two sets of 4 values. When you add a third dimension to your array, you create a set of sets. Create arrays of zeros with the following dimensions: [4,2], [4,3], [2,4,3], [4,2,3] and idenfity the sets of values.

In [12]:
np.zeros([4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros([2,4,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
array1 = np.zeros([4,2,3])
print(array1)
print(type(array1))
print(array1[1])
print(type(array1[1]))

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


Multidimensional NumPy arrays can be indexed just like one-dimensional array, but you need to specify each position within the index. 

For an example, run the following cells to print out the first value from the first row of the first set of a multimensional array:

In [20]:
sampleArray = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(sampleArray)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [21]:
print(sampleArray[0,0,0])

1


Notice that each dimension starts counting from zero. Here's the index to print out the last value in the second row of the second set:

In [25]:
print(sampleArray[1,1,3])

20


Your turn! Print out the following values from the array below using a multidimensional index:
- 6
- 2
- 8
- 1

In [22]:
array = np.array([[[6,0,5,3],[7,7,0,4],[9,3,0,2]],[[5,0,7,3],[0,4,8,9],[0,1,5,3]]])

# hint: print out the array to get a better sense of the sets of values
print(array)

[[[6 0 5 3]
  [7 7 0 4]
  [9 3 0 2]]

 [[5 0 7 3]
  [0 4 8 9]
  [0 1 5 3]]]


In [26]:
# hint: the first number in the index = the set, the second = the row, and the last = the value in that row
print(array[0,0,0])

6


In [28]:
print(array[0,2,3])

2


In [29]:
print(array[1,1,2])

8


In [30]:
print(array[1,2,1])

1
